### ISSUE TITLE
Hot Reload doesn't work in children element content

### ISSUE THREAD

**Issue by TimeZoom** [vuejs/vue-loader#1041]
### Version
13.4.0

### Reproduction link
[https://pastebin.com/Sq3m9Et2](https://pastebin.com/Sq3m9Et2)

### Steps to reproduce
vue init webpack foo

cd foo

npm install

npm run dev

Open src\components\HelloWorld.vue

if you create a new div and edit the content, hot reload wont work, but, if you edit before the element will work normaly

see: https://pastebin.com/Sq3m9Et2

### What is expected?
Edit content of element children div and hot reload it.

### What is actually happening?
When i edit the children element content wont reload

**Comment by LinusBorg** [comment]
pastebin is not a runnable reproduction. Use codesandbox.io or provide a github respository, please.

**Comment by TimeZoom** [comment]
Pastebin was only to point, for reproduce start a new project with vue-cli, and inside src\components\HelloWorld.vue or any other component if you create elements inside elements the children of it won't call hot reload.

**Comment by yyx990803** [comment]
Cannot reproduce... (this is unlikely a real bug, you probably have something wrong with your setup.)

**Comment by TimeZoom** [comment]
I tryed reproduce in another computer and same error, others browesers too, i think the problem is in template-compiler or in this new webpack-template (vue-cli).

When i activate the HMR log (noInfo=false) i had this log

[HMR] connected
client.js?4194:214 [HMR] bundle rebuilding
client.js?4194:222 [HMR] bundle rebuilt in 724ms
process-update.js?e13e:41 [HMR] Checking for updates on the server...
process-update.js?e13e:114 [HMR] Updated modules:
process-update.js?e13e:116 [HMR]  - ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-656039f0","hasScoped":true,"transformToRequire":{"video":"src","source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0&bustCache!./src/components/HelloWorld.vue
process-update.js?e13e:121 [HMR] App is up to date.

apparently the component is updating and calling the hot-reload, but isn't replaced.
That problem only happens where i edit content  from a second child of a template.

Example:

//Ok
<template>
  <div>
    Will Work
  </div>
</template>

//Dosn't call
<template>
  <div>
    Won't Work
    <div>Won't Work</div>
  </div>
</template>

**Comment by TimeZoom** [comment]
Reproduction link

https://github.com/TimeZoom/vue-loader-hotload

**Comment by yyx990803** [comment]
Thanks for the repro - this is a regression in Vue core 2.5.3.

**Comment by yyx990803** [comment]
This should be fixed with the latest version of `vue-hot-reload-api@2.2.3`

**Comment by TimeZoom** [comment]
Fixed! Worked!

I only did:
npm install --save vue@2.5.3

Thanks a lot

**Comment by lincenying** [comment]
good job..

**Comment by gbdematos** [comment]
I'm still having this problem.. even with `"vue": "2.5.3"` and `"vue-hot-reload-api": "^2.2.3"`.

**Comment by lincenying** [comment]
@gbdematos 
```sh
yarn add vue-hot-reload-api --dev
rm -rf node_modules
rm -rf yarn.lock
yarn install
```

**Comment by gbdematos** [comment]
@lincenying did it once, didn't solve the problem... tried again and now it's hot reloading properly. That's weird. 

Thanks for the help!

**Comment by lincenying** [comment]
May be the reason for the cache, part of the dependency is not updated to the latest
